name-template: 'Release $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  ## Changelog for $RESOLVED_VERSION

  $CHANGES

changelog:
  exclude:
    labels:
      - 'ignore for release'

  categories:
    - title: '🚀 New Features'
      labels:
        - 'enhancement'

    - title: '🐛 Bugs'
      labels:
        - 'bug'

    - title: '📚 Documentation'
      labels:
        - 'documentation'

    - title: '🔧 Maintenance'
      labels:
        - 'chore'

    - title: 'Other Changes'
      labels: []

autolabeler:
  - label: 'chore'
    files:
      - '*.md'

  - label: 'documentation'
    files:
      - 'docs/**'

  - label: 'bug'
    branch:
      - '/fix\/.+/'

  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
