name-template: 'Release $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  ## Changelog for $RESOLVED_VERSION

category-template: |
  ### $TITLE
  $CHANGES

changelog:
  exclude:
    labels:
      - "ignore for release"

  categories:
    - title: "🚀 New Features"
      labels:
        - enhancement

    - title: "🐛 Bugs"
      labels:
        - bug

    - title: "📚 Documentation"
      labels:
        - documentation

    - title: "Other Changes"
      labels: []
