name-template: 'Release $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |

  ## Changelog for $RESOLVED_VERSION

  ### 🚀 New Features
  $FEATURES

  ### 🐛 Bug Fixes
  $BUGS

  ### 📚 Documentation
  $DOCUMENTATION

  ### Other Changes
  $OTHER_CHANGES

changelog:
  exclude:
    labels:
      - "ignore for release"

  categories:
    - title: FEATURES
      labels:
        - enhancement

    - title: BUGS
      labels:
        - bug

    - title: DOCUMENTATION
      labels:
        - documentation

    - title: other_changes
      labels: []
