name: Manual CMake Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.25.0'

      - name: Create build directory
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Package binaries
        run: |
          mkdir -p artifacts
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp bin/Release/taskr.exe artifacts/taskr_${{ github.event.inputs.version }}_windows.exe
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            cp bin/taskr artifacts/taskr_${{ github.event.inputs.version }}_linux
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp bin/taskr artifacts/taskr_${{ github.event.inputs.version }}_macos
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: artifacts/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release notes from template
        id: draft_release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          tag: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        run: |
          gh release upload ${{ github.event.inputs.version }} \
            "artifacts/binaries-ubuntu-latest/taskr_${{ github.event.inputs.version }}_linux" \
            "artifacts/binaries-windows-latest/taskr_${{ github.event.inputs.version }}_windows.exe" \
            "artifacts/binaries-macos-latest/taskr_${{ github.event.inputs.version }}_macos" \
            --clobber

          gh release edit ${{ github.event.inputs.version }} --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
